version: 1.0.3.{build}
image: Visual Studio 2017
configuration: Release
environment:
  PROJECT_ROOT: C:\projects\sharppdb
install:
  - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
  - ps: choco install opencover.portable --limitoutput --no-progress
  - ps: choco install codecov --limitoutput --no-progress
before_build:
  - ps: Vsix-TokenReplacement SharedAssemblyInfo.props '<AssemblyVersion>([0-9\\.]+)</AssemblyVersion>' '<AssemblyVersion>{version}</AssemblyVersion>'
  - ps: Vsix-TokenReplacement SharedAssemblyInfo.props '<FileVersion>([0-9\\.]+)</FileVersion>' '<FileVersion>{version}</FileVersion>'
  - ps: Vsix-TokenReplacement SharedAssemblyInfo.props '<VersionPrefix>([0-9\\.]+)</VersionPrefix>' '<VersionPrefix>{version}</VersionPrefix>'
  - ps: pushd $env:PROJECT_ROOT\pdbs\
  - ps: .\download.ps1
  - ps: popd
build_script:
  - cmd: dotnet build /p:UsingAppVeyor=True
  - cmd: dotnet pack --no-build
test_script:
  - cmd: OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --no-build" -output:".\coverage.xml" -oldstyle -filter:"+[SharpPdb*]* -[SharpPdb*.Tests*]*"
  - cmd: codecov -f "coverage.xml"
artifacts:
- path: bin\**\*.nupkg
  name: NuGets
